services:
    sandbox_init_cms.menu.frontend_menu_builder:
        class: Networking\InitCmsBundle\Menu\FrontendMenuBuilder
        scope: request
        arguments:
            - @knp_menu.factory
            - @security.context
            - @request
            - @router
            - @networking_init_cms.menu_item_manager
            - @translator
            - @knp_menu.matcher


    # Create the left main menu and right main menu for the frontend
    sandbox_init_cms.menu.frontend_main_menu_left:
        class: Knp\Menu\MenuItem
        factory_service: sandbox_init_cms.menu.frontend_menu_builder
        factory_method: createMainMenu
        arguments: [menu_name: "Main menu", "nav nav-tabs nav-main" ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: mainMenu }

    sandbox_init_cms.menu.frontend_main_menu_language:
        class: Knp\Menu\MenuItem
        factory_service: sandbox_init_cms.menu.frontend_menu_builder
        factory_method: createFrontendLangMenu
        arguments: [ '@request', %networking_init_cms.page.languages%, "nav nav-pills pull-right" ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: langMenu }


    # Create the side menu for the frontend
    sandbox_init_cms.menu.frontend_sub_menu:
        class: Knp\Menu\MenuItem
        factory_service: sandbox_init_cms.menu.frontend_menu_builder
        factory_method: createSubnavMenu
        arguments: [ "Main menu", 'nav nav-pills']
        scope: request
        tags:
            - { name: knp_menu.menu, alias: subMenu }



    sandbox_init_cms.menu.frontend_footer_menu:
        class: Knp\Menu\MenuItem
        factory_service: sandbox_init_cms.menu.frontend_menu_builder
        factory_method: createFooterMenu
        arguments: ['Footer menu', 'nav nav-pills']
        scope: request
        tags:
            - { name: knp_menu.menu, alias: footerMenu }

