imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver:       pdo_sqlite
        path:         %kernel.cache_dir%/symfony.db
        host:         localhost
        dbname:       symfony
        user:         root
        password:     ~
        charset:      UTF8
        memory:       true