imports:
    - { resource: parameters.yml }
    - { resource: parameters_platform.php }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/cms_config.yml }


framework:
    #esi:             ~
    translator:      { fallback: 'en'}
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"



# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        mapping_types:
            enum: string


    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager:   default
        entity_managers:
            default:
                auto_mapping:     true
                connection:       default
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_sortable:
                        type: annotation
                        prefix: Gedmo\Sortable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Sortable/Entity"
                        alias: GedmoSortable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    FOSUserBundle: ~


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

networking_init_cms:
#    Activate the simple phpFastCache implementation to cache frontend files if in prod mode not logged in
    cache:
        activate: true #default false
        cache_time: 86400 #default value
        cache_service_class: Networking\InitCmsBundle\Lib\PhpCache #default value
    class:
        page: "Application\\Networking\\InitCmsBundle\\Entity\\Page"
        user: "Application\\Networking\\InitCmsBundle\\Entity\\User"
    languages:
        - {label: English, locale: en_US}
        - {label: Deutsch, locale: de_CH}
    templates:
        'Sandbox_one_column_template':
            template: "ApplicationNetworkingInitCmsBundle:Default:one_column.html.twig"
            name: "Single Column"
            icon: "bundles/applicationnetworkinginitcms/img/template_header_one_column.png"
            zones:
                - { name: header, class: 'col-md-12' }
                - { name: main_content, class: 'col-md-12'}
#                - { name: bottom, span:12}
        'Sandbox_two_column_template':
            template: "ApplicationNetworkingInitCmsBundle:Default:two_column.html.twig"
            name: "Two Column"
            icon: "bundles/applicationnetworkinginitcms/img/template_header_two_column.png"
            zones:
                - { name: header , class: 'col-md-12'}
                - { name: advertising , class: 'col-md-12', max_content_items: -1 }
                - { name: left , class: 'col-md-3'}
                - { name: right , class: 'col-md-9'}

    content_types:
        - { name: 'Text' , class: 'Networking\InitCmsBundle\Entity\Text'}
        - { name: 'Gallery' , class: 'Networking\InitCmsBundle\Entity\GalleryView'}

sonata_admin:
    title:      Demo Sailing Club

sonata_admin:
    templates:
        layout:     ApplicationNetworkingInitCmsBundle::admin_platform_layout.html.twig

lexik_translation:
    fallback_locale: en      # (required) default locale to use
    managed_locales: [en, de]    # (required) locales that the bundle have to manage

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name:  main
    user_class:     Application\Networking\InitCmsBundle\Entity\User
    group:
        group_class: Networking\InitCmsBundle\Entity\Group
    from_email:
            address:        webmaster@example.com
            sender_name:    web project

sonata_user:
    security_acl: true
    impersonating:
        route:                networking_init_cms_admin
        parameters:           { path: /}
    class:
        user: Application\Networking\InitCmsBundle\Entity\User
        group: Networking\InitCmsBundle\Entity\Group
    admin:                  # Admin Classes
        user:
            class:          Networking\InitCmsBundle\Admin\Entity\UserAdmin
            controller:     NetworkingInitCmsBundle:CRUD
            translation:    SonataUserBundle

        group:
            class:          Networking\InitCmsBundle\Admin\Entity\GroupAdmin
            controller:     NetworkingInitCmsBundle:CRUD
            translation:    SonataUserBundle



